# .github/FUNDING.yml
# Add your funding sources here. GitHub will display a "Sponsor" button automatically.

github: leli254     
open_collective: plutus   # Open Collective project name
patreon: plutus-project    # Optional Patreon
ko_fi:      # Optional Ko-fi
